// Copyright (c) 2021 Goosebump Designs
package com.goosebumpdesigns.cmdline.model;

import com.goosebumpdesigns.cmdline.HelpFormatter;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NonNull;
import lombok.ToString;

/**
 * This class maintains information about a parameter, which is an ordered non-option at the end of
 * the command line arguments. This is done as a Lombok-annnotated class instead of a record because
 * a record does not provide a builder. This class is immutable.
 * <p>
 * Parameters have long names but not short names. Parameter names are not specified by the
 * command-line arguments. They are only used in the help generated by the {@link HelpFormatter}.
 * <p>
 * Parameters may be specified as required. In this case they must be present on the command line
 * when it is parsed. You cannot add a required parameter after an optional parameter.
 * <p>
 * If you specify parameter help, it is displayed on the {@link HelpFormatter} when it generates the
 * command-line help.
 * 
 * @author Rob
 *
 */
@Getter
@EqualsAndHashCode
@ToString
@Builder
public class Parameter {
  @NonNull
  private String name;
  private boolean required;
  private String help;
}
